name: Deploy to GitHub Pages

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
      
    - name: "Install Dependencies"
      run: npm ci
      working-directory: Rucksackproblem
      
    - name: "Build static Website"
      run: npm run generate
      working-directory: Rucksackproblem
      
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.5.5
      with:
        BRANCH: dev
        FOLDER: Rucksackproblem/dist/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: master
        SINGLE_COMMIT: true
        CLEAN: true
